# pyproject.toml of black
[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
  \.git
  | \.mypy_cache
  | \.venv
  | _build
  | build
  | dist
)/
'''

# pyproject.toml of isort
[tool.isort]
py_version = 312
skip = ["__init__.py"]
skip_glob = ["migrations/*", ".venv/*", ".gitignore"]
multi_line_output = 3
include_trailing_comma = true